//---------------------------------------------------------------------------------------
// Whenever a `Clicked` event occurs on this actor, run `code` on it.
// If `code` returns `false`, continue waiting for next event, 
// otherwise, exit
//
// See: _on_begin_overlap_do, _on_end_overlap_do_until
//---------------------------------------------------------------------------------------

((Actor touched_actor Key button_pressed) Boolean code)
